name: moto_hud_nav
description: Moto HUD Navigation with OSRM + fallback
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.0
  geolocator: ^10.1.0
  http: ^1.2.0
  flutter_tts: ^3.8.5
  permission_handler: ^11.0.1

flutter:
  uses-material-design: true
